package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Candidatereports generated by hbm2java
 */
@Entity
@Table(name="candidatereports"
    ,catalog="imatchprofile"
)
public class Candidatereports  implements java.io.Serializable {


     private Integer candidatereportsId;
     private Candidate candidate;
     private User user;

    public Candidatereports() {
    }

    public Candidatereports(Candidate candidate, User user) {
       this.candidate = candidate;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="candidatereports_id", unique=true, nullable=false)
    public Integer getCandidatereportsId() {
        return this.candidatereportsId;
    }
    
    public void setCandidatereportsId(Integer candidatereportsId) {
        this.candidatereportsId = candidatereportsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="canditate_id", nullable=false)
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


