package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Candidate generated by hbm2java
 */
@Entity
@Table(name="candidate"
    ,catalog="imatchprofile"
)
public class Candidate  implements java.io.Serializable {


     private Integer candidateId;
     private User user;
     private String title;
     private String description;
     private String company;
     private byte visibility;
     private Set trainings = new HashSet(0);
     private Set experiences = new HashSet(0);
     private Set masterses = new HashSet(0);
     private Set applieses = new HashSet(0);
     private Set matcheses = new HashSet(0);
     private Set candidatereportses = new HashSet(0);
     private Set users = new HashSet(0);
     private Set chatrooms = new HashSet(0);
     private Set medias = new HashSet(0);

    public Candidate() {
    }

	
    public Candidate(User user, String title, String description, String company, byte visibility) {
        this.user = user;
        this.title = title;
        this.description = description;
        this.company = company;
        this.visibility = visibility;
    }
    public Candidate(User user, String title, String description, String company, byte visibility, Set trainings, Set experiences, Set masterses, Set applieses, Set matcheses, Set candidatereportses, Set users, Set chatrooms, Set medias) {
       this.user = user;
       this.title = title;
       this.description = description;
       this.company = company;
       this.visibility = visibility;
       this.trainings = trainings;
       this.experiences = experiences;
       this.masterses = masterses;
       this.applieses = applieses;
       this.matcheses = matcheses;
       this.candidatereportses = candidatereportses;
       this.users = users;
       this.chatrooms = chatrooms;
       this.medias = medias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="candidate_id", unique=true, nullable=false)
    public Integer getCandidateId() {
        return this.candidateId;
    }
    
    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="title", nullable=false, length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description", nullable=false, length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="company", nullable=false, length=45)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="visibility", nullable=false)
    public byte getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(byte visibility) {
        this.visibility = visibility;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getTrainings() {
        return this.trainings;
    }
    
    public void setTrainings(Set trainings) {
        this.trainings = trainings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getExperiences() {
        return this.experiences;
    }
    
    public void setExperiences(Set experiences) {
        this.experiences = experiences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getMasterses() {
        return this.masterses;
    }
    
    public void setMasterses(Set masterses) {
        this.masterses = masterses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getApplieses() {
        return this.applieses;
    }
    
    public void setApplieses(Set applieses) {
        this.applieses = applieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getMatcheses() {
        return this.matcheses;
    }
    
    public void setMatcheses(Set matcheses) {
        this.matcheses = matcheses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getCandidatereportses() {
        return this.candidatereportses;
    }
    
    public void setCandidatereportses(Set candidatereportses) {
        this.candidatereportses = candidatereportses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getChatrooms() {
        return this.chatrooms;
    }
    
    public void setChatrooms(Set chatrooms) {
        this.chatrooms = chatrooms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set medias) {
        this.medias = medias;
    }




}


