package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name="job"
    ,catalog="imatchprofile"
)
public class Job  implements java.io.Serializable {


     private Integer jobId;
     private Recruiter recruiter;
     private String title;
     private String description;
     private byte visibility;
     private Set applieses = new HashSet(0);
     private Set needses = new HashSet(0);
     private Set matcheses = new HashSet(0);
     private Set jobreportses = new HashSet(0);

    public Job() {
    }

	
    public Job(Recruiter recruiter, String title, String description, byte visibility) {
        this.recruiter = recruiter;
        this.title = title;
        this.description = description;
        this.visibility = visibility;
    }
    public Job(Recruiter recruiter, String title, String description, byte visibility, Set applieses, Set needses, Set matcheses, Set jobreportses) {
       this.recruiter = recruiter;
       this.title = title;
       this.description = description;
       this.visibility = visibility;
       this.applieses = applieses;
       this.needses = needses;
       this.matcheses = matcheses;
       this.jobreportses = jobreportses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="job_id", unique=true, nullable=false)
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="recruiter_id", nullable=false)
    public Recruiter getRecruiter() {
        return this.recruiter;
    }
    
    public void setRecruiter(Recruiter recruiter) {
        this.recruiter = recruiter;
    }

    
    @Column(name="title", nullable=false, length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description", nullable=false, length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="visibility", nullable=false)
    public byte getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(byte visibility) {
        this.visibility = visibility;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="job")
    public Set getApplieses() {
        return this.applieses;
    }
    
    public void setApplieses(Set applieses) {
        this.applieses = applieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="job")
    public Set getNeedses() {
        return this.needses;
    }
    
    public void setNeedses(Set needses) {
        this.needses = needses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="job")
    public Set getMatcheses() {
        return this.matcheses;
    }
    
    public void setMatcheses(Set matcheses) {
        this.matcheses = matcheses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="job")
    public Set getJobreportses() {
        return this.jobreportses;
    }
    
    public void setJobreportses(Set jobreportses) {
        this.jobreportses = jobreportses;
    }




}


