package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Masters generated by hbm2java
 */
@Entity
@Table(name="masters"
    ,catalog="imatchprofile"
)
public class Masters  implements java.io.Serializable {


     private Integer mastersId;
     private Candidate candidate;
     private Skill skill;

    public Masters() {
    }

    public Masters(Candidate candidate, Skill skill) {
       this.candidate = candidate;
       this.skill = skill;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="masters_id", unique=true, nullable=false)
    public Integer getMastersId() {
        return this.mastersId;
    }
    
    public void setMastersId(Integer mastersId) {
        this.mastersId = mastersId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id", nullable=false)
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="skill_id", nullable=false)
    public Skill getSkill() {
        return this.skill;
    }
    
    public void setSkill(Skill skill) {
        this.skill = skill;
    }




}


