package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Matches generated by hbm2java
 */
@Entity
@Table(name="matches"
    ,catalog="imatchprofile"
)
public class Matches  implements java.io.Serializable {


     private Integer matchesId;
     private Candidate candidate;
     private Job job;

    public Matches() {
    }

    public Matches(Candidate candidate, Job job) {
       this.candidate = candidate;
       this.job = job;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="matches_id", unique=true, nullable=false)
    public Integer getMatchesId() {
        return this.matchesId;
    }
    
    public void setMatchesId(Integer matchesId) {
        this.matchesId = matchesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id", nullable=false)
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_id", nullable=false)
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }




}


