package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name="media"
    ,catalog="imatchprofile"
)
public class Media  implements java.io.Serializable {


     private Integer mediaId;
     private Candidate candidate;
     private String path;

    public Media() {
    }

    public Media(Candidate candidate, String path) {
       this.candidate = candidate;
       this.path = path;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="media_id", unique=true, nullable=false)
    public Integer getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id", nullable=false)
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    
    @Column(name="path", nullable=false, length=300)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


