package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Needs generated by hbm2java
 */
@Entity
@Table(name="needs"
    ,catalog="imatchprofile"
)
public class Needs  implements java.io.Serializable {


     private Integer needsId;
     private Job job;
     private Skill skill;

    public Needs() {
    }

    public Needs(Job job, Skill skill) {
       this.job = job;
       this.skill = skill;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="needs_id", unique=true, nullable=false)
    public Integer getNeedsId() {
        return this.needsId;
    }
    
    public void setNeedsId(Integer needsId) {
        this.needsId = needsId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_id", nullable=false)
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="skill_id", nullable=false)
    public Skill getSkill() {
        return this.skill;
    }
    
    public void setSkill(Skill skill) {
        this.skill = skill;
    }




}


