package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recruiter generated by hbm2java
 */
@Entity
@Table(name="recruiter"
    ,catalog="imatchprofile"
)
public class Recruiter  implements java.io.Serializable {


     private Integer recruiterId;
     private User user;
     private String description;
     private String company;
     private Set chatrooms = new HashSet(0);
     private Set jobs = new HashSet(0);
     private Set users = new HashSet(0);

    public Recruiter() {
    }

	
    public Recruiter(User user, String description, String company) {
        this.user = user;
        this.description = description;
        this.company = company;
    }
    public Recruiter(User user, String description, String company, Set chatrooms, Set jobs, Set users) {
       this.user = user;
       this.description = description;
       this.company = company;
       this.chatrooms = chatrooms;
       this.jobs = jobs;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="recruiter_id", unique=true, nullable=false)
    public Integer getRecruiterId() {
        return this.recruiterId;
    }
    
    public void setRecruiterId(Integer recruiterId) {
        this.recruiterId = recruiterId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="description", nullable=false, length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="company", nullable=false, length=45)
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recruiter")
    public Set getChatrooms() {
        return this.chatrooms;
    }
    
    public void setChatrooms(Set chatrooms) {
        this.chatrooms = chatrooms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="recruiter")
    public Set getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Set jobs) {
        this.jobs = jobs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="candidate")
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


