package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name="skill"
    ,catalog="imatchprofile"
)
public class Skill  implements java.io.Serializable {


     private Integer skillId;
     private String title;
     private Set needses = new HashSet(0);
     private Set masterses = new HashSet(0);

    public Skill() {
    }

	
    public Skill(String title) {
        this.title = title;
    }
    public Skill(String title, Set needses, Set masterses) {
       this.title = title;
       this.needses = needses;
       this.masterses = masterses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="skill_id", unique=true, nullable=false)
    public Integer getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    
    @Column(name="title", nullable=false, length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="skill")
    public Set getNeedses() {
        return this.needses;
    }
    
    public void setNeedses(Set needses) {
        this.needses = needses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="skill")
    public Set getMasterses() {
        return this.masterses;
    }
    
    public void setMasterses(Set masterses) {
        this.masterses = masterses;
    }




}


