package com.imatchprofile.imatchprofile.model.pojo;
// Generated 8 déc. 2017 20:48:06 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Training generated by hbm2java
 */
@Entity
@Table(name="training"
    ,catalog="imatchprofile"
)
public class Training  implements java.io.Serializable {


     private Integer trainingId;
     private Candidate candidate;
     private String title;
     private String description;
     private Date startDate;
     private Date endDate;
     private String institute;

    public Training() {
    }

    public Training(Candidate candidate, String title, String description, Date startDate, Date endDate, String institute) {
       this.candidate = candidate;
       this.title = title;
       this.description = description;
       this.startDate = startDate;
       this.endDate = endDate;
       this.institute = institute;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="training_id", unique=true, nullable=false)
    public Integer getTrainingId() {
        return this.trainingId;
    }
    
    public void setTrainingId(Integer trainingId) {
        this.trainingId = trainingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="candidate_id", nullable=false)
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    
    @Column(name="title", nullable=false, length=45)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description", nullable=false, length=300)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", nullable=false, length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", nullable=false, length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="institute", nullable=false, length=45)
    public String getInstitute() {
        return this.institute;
    }
    
    public void setInstitute(String institute) {
        this.institute = institute;
    }




}


