package com.imatchprofile.model.pojo;
// Generated 27 d�c. 2017 17:10:07 by Hibernate Tools 4.3.1

import com.imatchprofile.model.pojo.Job;
import org.json.JSONObject;

/**
 * Applies generated by hbm2java
 */
public class Applies  implements java.io.Serializable {


     private Integer appliesId;
     private Candidate candidate;
     private Job job;

    public Applies() {
    }

    public Applies(Candidate candidate, Job job) {
       this.candidate = candidate;
       this.job = job;
    }
   
    public Integer getAppliesId() {
        return this.appliesId;
    }
    
    public void setAppliesId(Integer appliesId) {
        this.appliesId = appliesId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }

    public JSONObject toJSON() {
        JSONObject applyJSON = new JSONObject();
        
        applyJSON.put("apply_id", appliesId);
        applyJSON.put("candidate", candidate.toJSON());
        applyJSON.put("job", job.toJson());
        
        return applyJSON;
    }

}


