package com.imatchprofile.model.pojo;
// Generated 14 déc. 2017 20:28:42 by Hibernate Tools 4.3.1



/**
 * Applies generated by hbm2java
 */
public class Applies  implements java.io.Serializable {


     private Integer appliesId;
     private Candidate candidate;
     private Job job;

    public Applies() {
    }

    public Applies(Candidate candidate, Job job) {
       this.candidate = candidate;
       this.job = job;
    }
   
    public Integer getAppliesId() {
        return this.appliesId;
    }
    
    public void setAppliesId(Integer appliesId) {
        this.appliesId = appliesId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }




}


