package com.imatchprofile.model.pojo;
// Generated 27 déc. 2017 17:10:07 by Hibernate Tools 4.3.1



/**
 * Candidatereports generated by hbm2java
 */
public class Candidatereports  implements java.io.Serializable {


     private Integer candidatereportsId;
     private Candidate candidate;
     private User user;

    public Candidatereports() {
    }

    public Candidatereports(Candidate candidate, User user) {
       this.candidate = candidate;
       this.user = user;
    }
   
    public Integer getCandidatereportsId() {
        return this.candidatereportsId;
    }
    
    public void setCandidatereportsId(Integer candidatereportsId) {
        this.candidatereportsId = candidatereportsId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


