package com.imatchprofile.model.pojo;
// Generated 27 d�c. 2017 17:10:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.json.JSONObject;

/**
 * Candidate generated by hbm2java
 */
public class Candidate  implements java.io.Serializable {


     private Integer candidateId;
     private User user;
     private String title;
     private String description;
     private String company;
     private byte visibility;
     private Set trainings = new HashSet(0);
     private Set experiences = new HashSet(0);
     private Set masterses = new HashSet(0);
     private Set applieses = new HashSet(0);
     private Set matcheses = new HashSet(0);
     private Set candidatereportses = new HashSet(0);
     private Set users = new HashSet(0);
     private Set chatrooms = new HashSet(0);
     private Set medias = new HashSet(0);

    public Candidate() {
    }

	
    public Candidate(User user, String title, String description, String company, byte visibility) {
        this.user = user;
        this.title = title;
        this.description = description;
        this.company = company;
        this.visibility = visibility;
    }
    public Candidate(User user, String title, String description, String company, byte visibility, Set trainings, Set experiences, Set masterses, Set applieses, Set matcheses, Set candidatereportses, Set users, Set chatrooms, Set medias) {
       this.user = user;
       this.title = title;
       this.description = description;
       this.company = company;
       this.visibility = visibility;
       this.trainings = trainings;
       this.experiences = experiences;
       this.masterses = masterses;
       this.applieses = applieses;
       this.matcheses = matcheses;
       this.candidatereportses = candidatereportses;
       this.users = users;
       this.chatrooms = chatrooms;
       this.medias = medias;
    }
   
    public Integer getCandidateId() {
        return this.candidateId;
    }
    
    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public byte getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(byte visibility) {
        this.visibility = visibility;
    }
    public Set getTrainings() {
        return this.trainings;
    }
    
    public void setTrainings(Set trainings) {
        this.trainings = trainings;
    }
    public Set getExperiences() {
        return this.experiences;
    }
    
    public void setExperiences(Set experiences) {
        this.experiences = experiences;
    }
    public Set getMasterses() {
        return this.masterses;
    }
    
    public void setMasterses(Set masterses) {
        this.masterses = masterses;
    }
    public Set getApplieses() {
        return this.applieses;
    }
    
    public void setApplieses(Set applieses) {
        this.applieses = applieses;
    }
    public Set getMatcheses() {
        return this.matcheses;
    }
    
    public void setMatcheses(Set matcheses) {
        this.matcheses = matcheses;
    }
    public Set getCandidatereportses() {
        return this.candidatereportses;
    }
    
    public void setCandidatereportses(Set candidatereportses) {
        this.candidatereportses = candidatereportses;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getChatrooms() {
        return this.chatrooms;
    }
    
    public void setChatrooms(Set chatrooms) {
        this.chatrooms = chatrooms;
    }
    public Set getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set medias) {
        this.medias = medias;
    }

    public JSONObject toJSON() {
        JSONObject candidateJSON = new JSONObject();
        
        //info user
        candidateJSON.put("user_id", user.getUserId());
        candidateJSON.put("firstname", user.getFirstname());
        candidateJSON.put("lastname", user.getFirstname());
        candidateJSON.put("email", user.getEmail());
        candidateJSON.put("photoUrl", user.getPhotoUrl());
        //info candidat
        candidateJSON.put("candidate_id", candidateId);
        candidateJSON.put("title", title);
        candidateJSON.put("description", description);
        candidateJSON.put("company", company);
        candidateJSON.put("visibility", (visibility != 0));
        
        return candidateJSON;
    }
}


