package com.imatchprofile.model.pojo;
// Generated 27 déc. 2017 17:10:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Chatroom generated by hbm2java
 */
public class Chatroom  implements java.io.Serializable {


     private Integer chatroomId;
     private Candidate candidate;
     private Recruiter recruiter;
     private byte status;
     private Set messages = new HashSet(0);

    public Chatroom() {
    }

	
    public Chatroom(Candidate candidate, Recruiter recruiter, byte status) {
        this.candidate = candidate;
        this.recruiter = recruiter;
        this.status = status;
    }
    public Chatroom(Candidate candidate, Recruiter recruiter, byte status, Set messages) {
       this.candidate = candidate;
       this.recruiter = recruiter;
       this.status = status;
       this.messages = messages;
    }
   
    public Integer getChatroomId() {
        return this.chatroomId;
    }
    
    public void setChatroomId(Integer chatroomId) {
        this.chatroomId = chatroomId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public Recruiter getRecruiter() {
        return this.recruiter;
    }
    
    public void setRecruiter(Recruiter recruiter) {
        this.recruiter = recruiter;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }




}


