package com.imatchprofile.model.pojo;
// Generated 27 d�c. 2017 17:10:07 by Hibernate Tools 4.3.1


import com.imatchprofile.helper.DateHelper;
import java.util.Date;
import org.json.JSONObject;

/**
 * Experience generated by hbm2java
 */
public class Experience  implements java.io.Serializable {


     private Integer experienceId;
     private Candidate candidate;
     private String title;
     private String description;
     private Date startDate;
     private Date endDate;
     private String company;

    public Experience() {
    }

    public Experience(Candidate candidate, String title, String description, Date startDate, Date endDate, String company) {
       this.candidate = candidate;
       this.title = title;
       this.description = description;
       this.startDate = startDate;
       this.endDate = endDate;
       this.company = company;
    }
   
    public Integer getExperienceId() {
        return this.experienceId;
    }
    
    public void setExperienceId(Integer experienceId) {
        this.experienceId = experienceId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    public String toJSON() {
        JSONObject experienceJSON = new JSONObject();
        experienceJSON.put("experience_id", experienceId);
        experienceJSON.put("title", title);
        experienceJSON.put("description", description);
        experienceJSON.put("startDate", startDate);
        experienceJSON.put("endDate", endDate);
        experienceJSON.put("company", company);
        
        return experienceJSON.toString();
    }

    public JSONObject toJSONObject() {
        JSONObject experienceJSON = new JSONObject();
        experienceJSON.put("experience_id", experienceId);
        experienceJSON.put("title", title);
        experienceJSON.put("description", description);
        experienceJSON.put("start_date", DateHelper.getPrettyDate(startDate));
        experienceJSON.put("end_date", DateHelper.getPrettyDate(endDate));
        experienceJSON.put("company", company);
        
        return experienceJSON;
    }


}


