package com.imatchprofile.model.pojo;
// Generated 14 déc. 2017 20:28:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private Integer jobId;
     private Recruiter recruiter;
     private String title;
     private String description;
     private byte visibility;
     private Set applieses = new HashSet(0);
     private Set needses = new HashSet(0);
     private Set matcheses = new HashSet(0);
     private Set jobreportses = new HashSet(0);

    public Job() {
    }

	
    public Job(Recruiter recruiter, String title, String description, byte visibility) {
        this.recruiter = recruiter;
        this.title = title;
        this.description = description;
        this.visibility = visibility;
    }
    public Job(Recruiter recruiter, String title, String description, byte visibility, Set applieses, Set needses, Set matcheses, Set jobreportses) {
       this.recruiter = recruiter;
       this.title = title;
       this.description = description;
       this.visibility = visibility;
       this.applieses = applieses;
       this.needses = needses;
       this.matcheses = matcheses;
       this.jobreportses = jobreportses;
    }
   
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }
    public Recruiter getRecruiter() {
        return this.recruiter;
    }
    
    public void setRecruiter(Recruiter recruiter) {
        this.recruiter = recruiter;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(byte visibility) {
        this.visibility = visibility;
    }
    public Set getApplieses() {
        return this.applieses;
    }
    
    public void setApplieses(Set applieses) {
        this.applieses = applieses;
    }
    public Set getNeedses() {
        return this.needses;
    }
    
    public void setNeedses(Set needses) {
        this.needses = needses;
    }
    public Set getMatcheses() {
        return this.matcheses;
    }
    
    public void setMatcheses(Set matcheses) {
        this.matcheses = matcheses;
    }
    public Set getJobreportses() {
        return this.jobreportses;
    }
    
    public void setJobreportses(Set jobreportses) {
        this.jobreportses = jobreportses;
    }




}


