package com.imatchprofile.model.pojo;
// Generated 14 déc. 2017 20:28:42 by Hibernate Tools 4.3.1



/**
 * Jobreports generated by hbm2java
 */
public class Jobreports  implements java.io.Serializable {


     private Integer jobreportsId;
     private Job job;
     private User user;

    public Jobreports() {
    }

    public Jobreports(Job job, User user) {
       this.job = job;
       this.user = user;
    }
   
    public Integer getJobreportsId() {
        return this.jobreportsId;
    }
    
    public void setJobreportsId(Integer jobreportsId) {
        this.jobreportsId = jobreportsId;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


