package com.imatchprofile.model.pojo;
// Generated 27 déc. 2017 17:10:07 by Hibernate Tools 4.3.1



/**
 * Masters generated by hbm2java
 */
public class Masters  implements java.io.Serializable {


     private Integer mastersId;
     private Candidate candidate;
     private Skill skill;

    public Masters() {
    }

    public Masters(Candidate candidate, Skill skill) {
       this.candidate = candidate;
       this.skill = skill;
    }
   
    public Integer getMastersId() {
        return this.mastersId;
    }
    
    public void setMastersId(Integer mastersId) {
        this.mastersId = mastersId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public Skill getSkill() {
        return this.skill;
    }
    
    public void setSkill(Skill skill) {
        this.skill = skill;
    }




}


