package com.imatchprofile.model.pojo;
// Generated 27 d�c. 2017 17:10:07 by Hibernate Tools 4.3.1

import com.imatchprofile.model.pojo.Job;

/**
 * Matches generated by hbm2java
 */
public class Matches  implements java.io.Serializable {


     private Integer matchesId;
     private Candidate candidate;
     private Job job;

    public Matches() {
    }

    public Matches(Candidate candidate, Job job) {
       this.candidate = candidate;
       this.job = job;
    }
   
    public Integer getMatchesId() {
        return this.matchesId;
    }
    
    public void setMatchesId(Integer matchesId) {
        this.matchesId = matchesId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }




}


