package com.imatchprofile.model.pojo;
// Generated 27 d�c. 2017 17:10:07 by Hibernate Tools 4.3.1

import org.json.JSONObject;




/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private Integer mediaId;
     private Candidate candidate;
     private String path;

    public Media() {
    }

    public Media(Candidate candidate, String path) {
       this.candidate = candidate;
       this.path = path;
    }
   
    public Integer getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    public JSONObject toJSON() {
        JSONObject result = new JSONObject();
        result.put("media_id", getMediaId());
        result.put("path", getPath());
        result.put("filename", findNameFromPath());
        return result;
    } 
    
    private String findNameFromPath() {
        return path.substring(74);
    }
}


