package com.imatchprofile.model.pojo;
// Generated 14 déc. 2017 20:28:42 by Hibernate Tools 4.3.1



/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private Integer mediaId;
     private Candidate candidate;
     private String path;

    public Media() {
    }

    public Media(Candidate candidate, String path) {
       this.candidate = candidate;
       this.path = path;
    }
   
    public Integer getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


