package com.imatchprofile.model.pojo;
// Generated 27 déc. 2017 17:10:07 by Hibernate Tools 4.3.1



/**
 * Needs generated by hbm2java
 */
public class Needs  implements java.io.Serializable {


     private Integer needsId;
     private Job job;
     private Skill skill;

    public Needs() {
    }

    public Needs(Job job, Skill skill) {
       this.job = job;
       this.skill = skill;
    }
   
    public Integer getNeedsId() {
        return this.needsId;
    }
    
    public void setNeedsId(Integer needsId) {
        this.needsId = needsId;
    }
    public Job getJob() {
        return this.job;
    }
    
    public void setJob(Job job) {
        this.job = job;
    }
    public Skill getSkill() {
        return this.skill;
    }
    
    public void setSkill(Skill skill) {
        this.skill = skill;
    }




}


