package com.imatchprofile.model.pojo;
// Generated 27 d�c. 2017 17:10:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recruiter generated by hbm2java
 */
public class Recruiter  implements java.io.Serializable {


     private Integer recruiterId;
     private User user;
     private String description;
     private String company;
     private Set chatrooms = new HashSet(0);
     private Set jobs = new HashSet(0);
     private Set users = new HashSet(0);

    public Recruiter() {
    }

	
    public Recruiter(User user, String description, String company) {
        this.user = user;
        this.description = description;
        this.company = company;
    }
    public Recruiter(User user, String description, String company, Set chatrooms, Set jobs, Set users) {
       this.user = user;
       this.description = description;
       this.company = company;
       this.chatrooms = chatrooms;
       this.jobs = jobs;
       this.users = users;
    }
   
    public Integer getRecruiterId() {
        return this.recruiterId;
    }
    
    public void setRecruiterId(Integer recruiterId) {
        this.recruiterId = recruiterId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public Set getChatrooms() {
        return this.chatrooms;
    }
    
    public void setChatrooms(Set chatrooms) {
        this.chatrooms = chatrooms;
    }
    public Set getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Set jobs) {
        this.jobs = jobs;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }

    public String allJson(){
        StringBuilder json = new StringBuilder();
        json.append("{\n\"recruteurId\": \""+recruiterId+"\",\n");
        json.append("\"description\": \""+description+"\",\n");
        json.append("\"user\":"+user.toJSON()+",\n");
        json.append("\"company\": \""+company+"\"\n}");
        return json.toString();
    }

    @Override
    public String toString() {
        return "Recruiter{" + "recruiterId=" + recruiterId + ", user=" + user + ", description=" + description + ", company=" + company + ", chatrooms=" + chatrooms + ", jobs=" + jobs + ", users=" + users + '}';
    }



}


