package com.imatchprofile.model.pojo;
// Generated 27 d�c. 2017 17:10:07 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import org.json.JSONObject;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {
    private Integer userId;
    private Candidate candidate;
    private Moderator moderator;
    private Recruiter recruiter;
    private String lastname;
    private String firstname;
    private String email;
    private String password;
    private String photoUrl;
    private String role;
    private Set candidates = new HashSet(0);
    private Set candidatereportses = new HashSet(0);
    private Set recruiters = new HashSet(0);
    private Set jobreportses = new HashSet(0);
    private Set moderators = new HashSet(0);

    public User() {
    }

	
    public User(String lastname, String firstname, String email, String password) {
        this.lastname = lastname;
        this.firstname = firstname;
        this.email = email;
        this.password = password;
    }
    public User(Candidate candidate, Moderator moderator, Recruiter recruiter, String lastname, String firstname, String email, String password, String photoUrl, String role, Set candidates, Set candidatereportses, Set recruiters, Set jobreportses, Set moderators) {
       this.candidate = candidate;
       this.moderator = moderator;
       this.recruiter = recruiter;
       this.lastname = lastname;
       this.firstname = firstname;
       this.email = email;
       this.password = password;
       this.photoUrl = photoUrl;
       this.role = role;
       this.candidates = candidates;
       this.candidatereportses = candidatereportses;
       this.recruiters = recruiters;
       this.jobreportses = jobreportses;
       this.moderators = moderators;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Candidate getCandidate() {
        return this.candidate;
    }
    
    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }
    public Moderator getModerator() {
        return this.moderator;
    }
    
    public void setModerator(Moderator moderator) {
        this.moderator = moderator;
    }
    public Recruiter getRecruiter() {
        return this.recruiter;
    }
    
    public void setRecruiter(Recruiter recruiter) {
        this.recruiter = recruiter;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhotoUrl() {
        return this.photoUrl;
    }
    
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getCandidates() {
        return this.candidates;
    }
    
    public void setCandidates(Set candidates) {
        this.candidates = candidates;
    }
    public Set getCandidatereportses() {
        return this.candidatereportses;
    }
    
    public void setCandidatereportses(Set candidatereportses) {
        this.candidatereportses = candidatereportses;
    }
    public Set getRecruiters() {
        return this.recruiters;
    }
    
    public void setRecruiters(Set recruiters) {
        this.recruiters = recruiters;
    }
    public Set getJobreportses() {
        return this.jobreportses;
    }
    
    public void setJobreportses(Set jobreportses) {
        this.jobreportses = jobreportses;
    }
    public Set getModerators() {
        return this.moderators;
    }
    
    public void setModerators(Set moderators) {
        this.moderators = moderators;
    }
    
    public JSONObject toJSON(){
        JSONObject userJSON = new JSONObject();
        userJSON.put("user_id", this.userId);
        userJSON.put("lastname", this.lastname);
        userJSON.put("firstname", this.firstname);
        userJSON.put("email", this.email);
        userJSON.put("photoUrl", this.photoUrl);
        userJSON.put("role", this.role);
        switch (this.role){
            case "C":
                userJSON.put("sub_user_id", this.candidate.getCandidateId());
                break;
            case "R":
                userJSON.put("sub_user_id", this.recruiter.getRecruiterId());
                break;
            case "M":
                userJSON.put("sub_user_id", this.moderator.getModeratorId());
                break;
        }
        
        return userJSON;
    }

    @Override
    public String toString() {
        return "User{" + "userId=" + userId + ", candidate=" + candidate + ", moderator=" + moderator + ", recruiter=" + recruiter + ", lastname=" + lastname + ", firstname=" + firstname + ", email=" + email + ", password=" + password + ", photoUrl=" + photoUrl + ", role=" + role + ", candidates=" + candidates + ", candidatereportses=" + candidatereportses + ", recruiters=" + recruiters + ", jobreportses=" + jobreportses + ", moderators=" + moderators + '}';
    }
    
    
}


